AWSTemplateFormatVersion: 2010-09-09
Description: wishlist-api-sam

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Default: Prod
  Auth0Domain:
    Type: String

Resources:
  WishlistTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  getItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get-items.getItemsHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: an HTTP get method to get all my items from WishList DynamoDB table.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WishlistTable
      Environment:
        Variables:
          TABLE_NAME: !Ref WishlistTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /wishlist
            Method: GET
            ApiId: !Ref WishlistAPI
            Auth:
              Authorizer: Auth0Authorizer
              AuthorizationScopes:
                - read:items

  postItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/post-item.postItemHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: an HTTP POST method to create a new item in WishList DynamoDB table.
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref WishlistTable
      Environment:
        Variables:
          TABLE_NAME: !Ref WishlistTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /wishlist
            Method: POST
            ApiId: !Ref WishlistAPI
            Auth:
              Authorizer: Auth0Authorizer
              AuthorizationScopes:
                - create:item

  deleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/delete-item.deleteItemHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: an HTTP DELETE method to delete an item from WishList DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WishlistTable
      Environment:
        Variables:
          TABLE_NAME: !Ref WishlistTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /wishlist/{id}
            Method: DELETE
            ApiId: !Ref WishlistAPI
            Auth:
              Authorizer: Auth0Authorizer
              AuthorizationScopes:
                - delete:item

  WishlistAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      FailOnWarnings: True
      Auth:
        Authorizers:
          Auth0Authorizer:
            JwtConfiguration:
              issuer: !Sub "https://${Auth0Domain}/"
              audience:
                - https://wishlist.api
            IdentitySource: $request.header.Authorization
        DefaultAuthorizer: Auth0Authorizer

Outputs:
  Shutdown:
    Description: CloudFormation Delete Command
    Value: !Sub "aws cloudformation delete-stack --stack-name ${AWS::StackName}"

  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub 'https://${WishlistAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/wishlist'
